### ISSUE TITLE
Sweep: Do not install latest npm in github workflow npm-build.yml

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/workflows#2]
Do not install latest npm in github workflow npm-build.yml
https://github.com/deep-foundation/workflows/blob/d12184a1d834a379abd2d907e50e7c555887a66c/.github/workflows/npm-build.yml#L23

<details open>
<summary>Checklist</summary>

- [X] Modify `.github/workflows/npm-build.yml` ✓ https://github.com/deep-foundation/workflows/commit/05e41027c49f6765218f6eec175341df3ffa8d23

![Flowchart](https://raw.githubusercontent.com/deep-foundation/workflows/sweep/assets/b5f619e678a9ec07a908947c0edf027df9221b6bc8fcb15f36eac0ebf4f7b710_2_flowchart.svg)
</details>

**Comment by FreePhoenix888** [comment]
Sweep: retry

**Comment by FreePhoenix888** [comment]
Sweep: retry

**Comment by konard** [comment]
@FreePhoenix888 what is the problem with installation of latest npm? It usually fixes lots of problems, so it may safely stay.

I suggest to close this issue as `not planned`.

Linked pull request may be closed too.
